const PRODUCTS=[
{id:'veste-bleue',name:'Veste bleu signature',category:'vestes',color:'Bleu cobalt',images:[1],description:'Une veste bleue à col et poches plaquées, portée sur un haut blanc. Une ligne décontractée, une couleur qui affirme le style.'},
{id:'chemise-bordeaux',name:'Chemise bordeaux',category:'chemises',color:'Bordeaux',images:[2],description:'Une chemise à manches courtes et à la coupe ample. Le bordeaux contraste avec un pantalon clair pour une allure simple et affirmée.'},
{id:'surchemise-olive',name:'Surchemise olive',category:'vestes',color:'Olive, détails contrastés',images:[3,4],description:'Une surchemise olive à poches contrastées. Découvrez la pièce de face et de dos pour apprécier ses détails graphiques.'},
{id:'polo-colourblock',name:'Polo color block',category:'graphiques',color:'Bleu, rose & écru',images:[5],description:'Un polo aux aplats de couleurs et à la bande graphique contrastée, photographié sur le podium. Une silhouette à l’esprit sportif.'},
{id:'veste-rouge',name:'Veste rouge graphique',category:'vestes',color:'Rouge & beige',images:[6],description:'Un rouge profond, un large empiècement beige et une signature graphique au dos. Une pièce qui se distingue par ses contrastes.'},
{id:'chemises-graphiques',name:'Chemises graphiques',category:'graphiques',color:'Bleu ou rouge multicolore',images:[7,9,16],description:'Deux compositions graphiques, une même liberté d’allure. Les motifs colorés se portent avec des volumes décontractés. Précisez le coloris souhaité auprès de la marque.'},
{id:'surchemise-bleue',name:'Surchemise bleu profond',category:'chemises',color:'Bleu',images:[8,13],description:'Une surchemise à manches longues et à poches poitrine. Une silhouette sobre, portée ici avec un short sombre.'},
{id:'silhouette-rouge',name:'Silhouette rouge & blanc',category:'silhouettes',color:'Rouge & blanc',images:[10],description:'Une veste rouge à boutons contrastés, associée à un short blanc. Contactez la marque pour connaître les pièces disponibles séparément.'},
{id:'silhouette-noire',name:'Silhouette noire',category:'silhouettes',color:'Noir',images:[11],description:'Une silhouette noire aux lignes nettes et aux détails contrastés. Une proposition d’allure à découvrir auprès de M.I.C.I.'},
{id:'chemise-sport',name:'Chemise esprit sport',category:'chemises',color:'Écru, rose & rouge',images:[15,12],description:'Une chemise ample à manches courtes, avec une bande rose et des marquages graphiques rouges. Découvrez les vues de face et de profil.'},
{id:'duo-lilas',name:'Chemise lilas contrastée',category:'chemises',color:'Lilas, orange & turquoise',images:[14],description:'Une chemise lilas à manches courtes, rehaussée de bandes orange et turquoise. Présentée ici sur deux silhouettes.'},
{id:'surchemise-noire',name:'Surchemise noire contrastée',category:'vestes',color:'Noir, détails colorés',images:[17],description:'Une surchemise noire à col et poches aux empiècements colorés. Photographiée sur le portant de la collection.'},
{id:'sac-weekend',name:'Sac week-end',category:'accessoires',color:'Noir & orange',images:[18],description:'Un sac à anses aux lignes arrondies, avec des sangles orange et un panneau latéral contrasté. Dimensions et disponibilité à confirmer auprès de M.I.C.I.'}
];
const LABELS={vestes:'Vestes & surchemises',chemises:'Chemises',graphiques:'Pièces graphiques',silhouettes:'Silhouettes',accessoires:'Accessoires'};
const src=i=>`article-${String(i).padStart(2,'0')}.jpg`;
const $=s=>document.querySelector(s);let favorites=new Set();try{const saved=JSON.parse(localStorage.getItem('mici-favorites')||'[]');if(Array.isArray(saved))favorites=new Set(saved.filter(id=>PRODUCTS.some(p=>p.id===id)))}catch{}
let filter='all',selected=null,toastTimer;const grid=$('#product-grid'),dialog=$('#product-dialog');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300)}
function updateCount(){$('#favorite-count').textContent=favorites.size;$('#favorites-open').setAttribute('aria-label',`Voir mes favoris (${favorites.size})`)}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);try{localStorage.setItem('mici-favorites',JSON.stringify([...favorites]))}catch{}updateCount();render();if(selected)updateDetailFavorite();toast(favorites.has(id)?'Pièce ajoutée à vos favoris.':'Pièce retirée de vos favoris.')}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function render(){const query=normalize($('#search').value.trim());const list=PRODUCTS.filter(p=>(filter==='all'||(filter==='favorites'?favorites.has(p.id):p.category===filter))&&normalize(`${p.name} ${p.color} ${LABELS[p.category]}`).includes(query));grid.replaceChildren();for(const p of list){let card=document.createElement('article');card.className='product';card.innerHTML=`<button class="product-open" aria-label="Voir ${p.name}"><div class="product-photo"><img src="${src(p.images[0])}" alt="${p.name} M.I.C.I." loading="lazy"><span class="product-view">Découvrir la pièce ⟶</span></div><div class="product-meta"><span>${p.name}</span><span>↗</span></div><p class="product-sub">${p.color}</p></button><button class="fav${favorites.has(p.id)?' selected':''}" aria-pressed="${favorites.has(p.id)}" aria-label="${favorites.has(p.id)?'Retirer':'Ajouter'} ${p.name} ${favorites.has(p.id)?'des':'aux'} favoris">${favorites.has(p.id)?'♥':'♡'}</button>`;card.querySelector('.product-open').onclick=()=>openProduct(p);card.querySelector('.fav').onclick=()=>toggleFavorite(p.id);grid.append(card)}$('#result-count').textContent=`${list.length} pièce${list.length>1?'s':''}`;$('#empty').hidden=list.length>0}
function setFilter(value,clear=false){filter=value;if(clear)$('#search').value='';document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===filter;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});render()}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.filter));document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>setFilter(a.dataset.category,true));$('#search').addEventListener('input',render);$('#reset-filter').onclick=()=>setFilter('all',true);
function showFavorites(){setFilter('favorites',true);$('#catalogue').scrollIntoView({behavior:reduced?'instant':'smooth'})}$('#favorites-open').onclick=showFavorites;$('#footer-favorites').onclick=showFavorites;$('#search-open').onclick=()=>{$('#catalogue').scrollIntoView({behavior:reduced?'instant':'smooth'});$('#search').focus({preventScroll:true})};
function updateDetailFavorite(){const active=favorites.has(selected.id);$('#detail-favorite').textContent=active?'♥ Retirer des favoris':'♡ Ajouter aux favoris';$('#detail-favorite').setAttribute('aria-pressed',String(active))}
function openProduct(p){selected=p;$('#detail-title').textContent=p.name;$('#detail-category').textContent=LABELS[p.category];$('#detail-description').textContent=p.description;$('#detail-color').textContent=p.color;$('#copy-status').textContent='';$('#detail-thumbs').replaceChildren();function showImage(index){$('#detail-image').src=src(p.images[index]);$('#detail-image').alt=`${p.name} — vue ${index+1}`;$('#detail-thumbs').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-pressed',String(i===index))})}p.images.forEach((id,index)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Afficher la vue ${index+1}`);b.innerHTML=`<img src="${src(id)}" alt="">`;b.onclick=()=>showImage(index);$('#detail-thumbs').append(b)});$('#detail-thumbs').hidden=p.images.length<2;showImage(0);updateDetailFavorite();dialog.showModal();document.body.classList.add('locked')}
$('#detail-favorite').onclick=()=>toggleFavorite(selected.id);$('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>document.body.classList.remove('locked'));dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});
$('#copy-request').onclick=async()=>{const text=`Bonjour M.I.C.I., je suis intéressé(e) par « ${selected.name} » (${selected.color}). Pouvez-vous m’indiquer son prix, les tailles disponibles et les modalités de commande ? Merci !`;let success=false;try{await navigator.clipboard.writeText(text);success=true}catch{const t=document.createElement('textarea');t.value=text;dialog.append(t);t.select();try{success=document.execCommand('copy')}catch{}t.remove()}$('#copy-status').textContent=success?'Demande copiée. Vous pouvez la coller sur Instagram.':text};
const menu=$('#menu-toggle'),mobile=$('#mobile-menu');function closeMenu(){mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Ouvrir le menu')}menu.onclick=()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu')};mobile.querySelectorAll('a').forEach(a=>a.onclick=closeMenu);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobile.hidden){closeMenu();menu.focus()}});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,video=$('#hero-video');function updateVideo(){$('#video-toggle').setAttribute('aria-label',video.paused?'Lire la vidéo':'Mettre la vidéo en pause');$('#video-symbol').textContent=video.paused?'▷':'Ⅱ';$('#video-label').textContent=video.paused?'Lire':'Pause'}video.addEventListener('play',updateVideo);video.addEventListener('pause',updateVideo);video.addEventListener('error',()=>{$('#video-label').textContent='Vidéo indisponible'});$('#video-toggle').onclick=async()=>{if(video.paused){try{await video.play()}catch{toast('La vidéo ne peut pas être lue dans ce navigateur.')}}else video.pause();updateVideo()};if(reduced){video.autoplay=false;video.pause()}else video.play().catch(updateVideo);updateVideo();
if('IntersectionObserver'in window&&!reduced){document.documentElement.classList.add('js-motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
$('#year').textContent=new Date().getFullYear();updateCount();render();
